// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "15670891-a55c-42be-a8dd-f644f8449cbf");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1619360780);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1619360754);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1619360885);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1619360914);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1619360944);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 808960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1619360750);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fe5bf70a-3116-48f4-9921-2c0fb5dbee99}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1619360785144");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1619362590144");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1619360752573");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1619382352573");
user_pref("browser.search.region", "US");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1619360885");
user_pref("browser.slowStartup.averageTime", 1514);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210315154203");
user_pref("browser.startup.homepage_override.mstone", "78.9.0");
user_pref("browser.startup.lastColdStartupCheck", 1619360884);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.SLE.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.9.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "0655c0e8ac4c4324ae2ab547ec3d72de");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210315154203");
user_pref("extensions.lastAppVersion", "78.9.0");
user_pref("extensions.lastPlatformVersion", "78.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"130d4770-9638-48b5-ba51-cd5e7c7a37ff\",\"formautofill@mozilla.org\":\"9c196f36-c690-47ed-82d1-8a398f352eb4\",\"screenshots@mozilla.org\":\"0e0cb410-ff38-4b3f-8fff-de149f0a633c\",\"webcompat-reporter@mozilla.org\":\"42183b32-5033-4f28-9a9b-c4cbcf383cf4\",\"webcompat@mozilla.org\":\"71149bf5-d5d9-4c92-80ac-6f44c10f4af9\",\"default-theme@mozilla.org\":\"78a286ac-992f-4bbb-aef0-ca78a9ecca43\",\"google@search.mozilla.org\":\"8b019741-fb86-4084-8376-744de85eeb2b\",\"amazondotcom@search.mozilla.org\":\"3a38f449-7eef-4566-ae01-60152d26aea4\",\"wikipedia@search.mozilla.org\":\"6053a508-d61f-4fab-9fe5-7175e09c6bdf\",\"bing@search.mozilla.org\":\"ee482a6d-8e3c-4f4b-84bf-cc3943845337\",\"ddg@search.mozilla.org\":\"e7514bc4-2cf1-4a0c-b2f3-18a2c4cbfbf0\",\"ebay@search.mozilla.org\":\"6edc2580-0286-4cf0-a1cc-b4a02d533c33\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1619360771);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20210315154203");
user_pref("media.gmp-manager.lastCheck", 1619360771);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1619375171);
user_pref("security.remote_settings.intermediates.checked", 1619375171);
user_pref("security.sandbox.content.tempDirSuffix", "bb6e7860-34f0-4077-9d09-4189bc0ea583");
user_pref("security.sandbox.plugin.tempDirSuffix", "0868de0e-e864-417e-a3df-5605c5bf0e03");
user_pref("services.blocklist.addons-mlbf.checked", 1619375171);
user_pref("services.blocklist.gfx.checked", 1619375171);
user_pref("services.blocklist.pinning.checked", 1619375171);
user_pref("services.blocklist.plugins.checked", 1619375171);
user_pref("services.settings.clock_skew_seconds", -14401);
user_pref("services.settings.last_etag", "\"1619359120525\"");
user_pref("services.settings.last_update_seconds", 1619375171);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1619375171);
user_pref("services.settings.main.cfr-fxa.last_check", 1619375171);
user_pref("services.settings.main.cfr.last_check", 1619375171);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1619375171);
user_pref("services.settings.main.hijack-blocklists.last_check", 1619375171);
user_pref("services.settings.main.language-dictionaries.last_check", 1619375171);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1619375171);
user_pref("services.settings.main.public-suffix-list.last_check", 1619375171);
user_pref("services.settings.main.search-config.last_check", 1619375171);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1619375171);
user_pref("services.settings.main.sites-classification.last_check", 1619375171);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1619375171);
user_pref("services.settings.main.whats-new-panel.last_check", 1619375171);
user_pref("services.settings.security.onecrl.checked", 1619375171);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1619360883);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210315154203");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
